--- 
title: "Using remote camera trap images to estimate densities and develop habitat models for mammals in Alberta, Canada"
author: "Marcus Becker, Dr. David J. Huggard, Dr. David Roberts"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  ABMI Camera Methods and Mammal Modeling
link-citations: yes
github-repo: "ABbiodiversity/MammalModels"
---

# Introduction

The Alberta Biodiversity Monitoring Institute (ABMI) has developed a monitoring program for mammals within the province of Alberta, Canada. This technical document contains information describing how the image data from remote camera traps deployed across the province is collected, processed, and analyzed. 

This document will be updated as necessary to reflect changes in available data, deployment protocols, and modeling procedures. Readers are also encouraged to visit the ABMI's [Biodiversity Browser](https://www.abmi.ca/home/data-analytics/biobrowser-home) for current mammal species results.

## Acknowledgement

We would like to acknowledge that this work would not be possible without the dedication of the ABMI staff, both past and present. Field staff, geospatial experts, taxonomists, image taggers, and ecologists have all been integral components to this work. 

## Suggested Citation

Alberta Biodiversity Monitoring Institute. 2024. Using remote camera trap images to estimate densities and develop habitat models for mammals in Alberta, Canada. Alberta Biodiversity Monitoring Institute, Alberta, Canada. (https://abbiodiversity.github.io/MammalModels/).

## Contact

For all questions related to this document, the code therein, or acquiring raw image data, please contact Marcus Becker (marcus.becker@ualberta.ca). 
